import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored Cesium static assets, regenerated by scripts/copy-cesium-assets.mjs.
    "public/cesium/**",
    // Same, for MapLibre's tile-parsing worker — scripts/copy-maplibre-assets.mjs.
    "public/maplibre/**",
  ]),
]);

export default eslintConfig;
