import { parseJsonResponse, runClaude } from "../../claude";
import type { BenchFixture } from "../fixtures";
import type { JudgeScore } from "../types";

/**
 * The optional model-judged quality score. OFF unless the caller explicitly asks for it — every
 * other scorer in this harness is deterministic, and mixing a model's opinion into that silently
 * would undermine the whole point.
 *
 * Three blinding measures, all of them load-bearing:
 *  1. **Identity stripped.** Model names, vendor names and any "generated by" line are scrubbed
 *     from each itinerary before the judge sees it.
 *  2. **Order randomized, but seeded.** Presentation order is shuffled from a hash of the fixture
 *     id, so position bias can't line up with the model list — and the same fixture shuffles the
 *     same way on every run, which keeps the judged numbers reproducible.
 *  3. **One fixed judge for every output.** All candidates for a trip are scored in a single call,
 *     against each other, by one model — so the scores are comparable within a trip.
 *
 * WHAT THIS DOES NOT FIX, and the UI says so next to every judged number: the judge is a Claude
 * model scoring Claude models. If the judge is also one of the candidates, it is grading its own
 * work. Judges systematically favour outputs that resemble their own style, reward length and
 * confident phrasing, and cannot verify a single fact in the plan. Treat these as a soft preference
 * signal, never as ground truth — the deterministic scorers are what the harness is actually for.
 */

export const DEFAULT_JUDGE_MODEL = "claude-opus-5";

export function judgeModel(): string {
  return process.env.BENCH_JUDGE_MODEL ?? DEFAULT_JUDGE_MODEL;
}

const JUDGE_TIMEOUT_MS = 240_000;

/** Anything that could leak which model wrote a candidate. */
const IDENTITY_PATTERNS: RegExp[] = [
  /\bclaude[\w.-]*\b/gi,
  /\b(anthropic|opus|sonnet|haiku|fable|mythos|gpt|gemini|llama|mistral)\b/gi,
  /\b(generated|written|produced|created)\s+by\s+[^\n.]{0,40}/gi,
  /\bas an ai\b[^\n.]{0,60}/gi,
];

export function stripIdentity(markdown: string): string {
  return IDENTITY_PATTERNS.reduce((text, pattern) => text.replace(pattern, "[redacted]"), markdown);
}

/** Deterministic PRNG so a fixture's presentation order is stable across runs. */
function seededRandom(seed: string): () => number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) {
    h ^= seed.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  let state = h >>> 0;
  return () => {
    state |= 0;
    state = (state + 0x6d2b79f5) | 0;
    let t = Math.imul(state ^ (state >>> 15), 1 | state);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function seededShuffle<T>(items: T[], seed: string): T[] {
  const rng = seededRandom(seed);
  const out = [...items];
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

const LABELS = "ABCDEFGH".split("");

interface JudgeCandidate {
  model: string;
  itineraryMd: string;
}

interface JudgeVerdict {
  label: string;
  desirability: number;
  realism: number;
  rationale: string;
}

function buildJudgePrompt(fixture: BenchFixture, shuffled: JudgeCandidate[]): string {
  const a = fixture.reconciled.userAnswers;
  const f = fixture.reconciled.resolvedFlags;

  const brief = [
    `Destination: ${fixture.reconciled.rawFetch.destination.region}`,
    `Length: ${fixture.reconciled.rawFetch.dateContext.tripDays} days`,
    `Traveler: ${a.group}, ${a.energy} energy, ${a.crowds} crowds, ${a.explorerStyle} style`,
    `Pace target: ${f.paceResolved} (${f.paceSpotsPerDay} stops/day)`,
    `Top priorities: ${f.prioritiesRanked.primary.join(", ") || "none"}`,
    `Purpose: ${a.purpose}`,
    `Budget: $${a.budget}`,
  ].join("\n");

  const candidates = shuffled
    .map(
      (c, i) =>
        `<candidate label="${LABELS[i]}">\n${stripIdentity(c.itineraryMd)}\n</candidate>`
    )
    .join("\n\n");

  return `You are scoring candidate travel itineraries written for the same traveler brief. You do not know who or what wrote them, and you must not speculate.

<brief>
${brief}
</brief>

${candidates}

Score every candidate on two axes, each an integer from 1 to 10:
- desirability: would this traveler actually enjoy this trip, given their stated profile and priorities?
- realism: could a real person execute this day-by-day without the plan falling apart?

Judge only what is written. Do not reward length, formatting polish, or confident phrasing. Score each candidate on its own merits rather than ranking them into a fixed spread — ties are fine.

Respond with only this JSON, no preamble and no code fences:
{"verdicts":[{"label":"A","desirability":7,"realism":8,"rationale":"one sentence"}]}`;
}

/**
 * Scores every candidate for one fixture in a single blinded call. Returns a map keyed by model id.
 * Fails soft: a judge error leaves the cells' `judge` field null rather than failing the run.
 */
export async function judgeFixture(
  fixture: BenchFixture,
  candidates: JudgeCandidate[],
  runId?: string
): Promise<Record<string, JudgeScore>> {
  if (candidates.length === 0) return {};

  const shuffled = seededShuffle(candidates, fixture.id);
  const prompt = buildJudgePrompt(fixture, shuffled);

  const { result } = await runClaude(prompt, "judge", JUDGE_TIMEOUT_MS, {
    runId,
    model: judgeModel(),
  });

  const parsed = parseJsonResponse<{ verdicts: JudgeVerdict[] }>(result);
  const byLabel = new Map(parsed.verdicts.map((v) => [v.label.trim().toUpperCase(), v]));

  const scores: Record<string, JudgeScore> = {};
  shuffled.forEach((candidate, i) => {
    const label = LABELS[i];
    const verdict = byLabel.get(label);
    if (!verdict) return;
    const desirability = Number(verdict.desirability);
    const realism = Number(verdict.realism);
    if (!Number.isFinite(desirability) || !Number.isFinite(realism)) return;
    scores[candidate.model] = {
      desirability,
      realism,
      overall: (desirability + realism) / 2,
      rationale: verdict.rationale ?? "",
      blindLabel: label,
    };
  });

  return scores;
}
