// GENERATED by scripts/build-frame-sequence.mjs — do not edit by hand.
//
// Petra, Al-Khazneh through the Siq: a dolly from inside the canyon, opening onto the Treasury,
// closing on the facade. 100 frames sampled by equal visual change from unique source
// frames 1..240 of 240, less .

export const HERO_SEQUENCE = {
  frames: 100,
  /** Frame 1, full quality, for `next/image`. The canvas's first draw is this same frame, so the
   *  hand-off from poster to canvas is a visual no-op. */
  poster: "/scenes/petra/0329455b/poster.webp",
  tiers: [
    { id: "land", w: 1600, h: 900 },
    { id: "port", w: 540, h: 960 },
  ],
} as const;

export type HeroTierId = (typeof HERO_SEQUENCE.tiers)[number]["id"];

/** 1-based on disk, so callers pass 0-based and this shifts. */
export function heroFrameUrl(tier: HeroTierId, index: number): string {
  return `/scenes/petra/0329455b/${tier}-${String(index + 1).padStart(3, "0")}.avif`;
}
